### ISSUE TITLE
Estimated timeline of CFU-Playground integration

### ISSUE THREAD

**Issue by Msabih** [srivatsankrishnan/oss-arch-gym#10]
Hi,

Congratulations for this well-needed contribution. I would like to know if you have an estimated timeline about when the CFU-Playground is supposed to be integrated? Also, do you welcome contributions in this area?

**Comment by srivatsankrishnan** [comment]
Thanks for your interest. @ShvetankPrakash is currently leading this effort on integrating CFU with ArchGym and I will let him comment on this. 

Regarding welcoming contributions, we definitely welcome any contributions on this or any other simulator that community can benefit.

**Comment by ShvetankPrakash** [comment]
Thanks for your interest @Msabih! We are in the progress of integrating CFU-Playground and close to being done. We expect to be done with this in the next 10 days most likely! Is there a specific deadline you have for which you would like to use CFU Playground + ArchGym?

**Comment by Msabih** [comment]
We wanted to start using it by mid-August to end-August.

**Comment by ShvetankPrakash** [comment]
Hi @Msabih the integration has been completed. See #17  and feel free to give it a test to let us know how it goes! If there are any problems please post another separate Github Issue and we will work to get anything resolved quickly.
