### ISSUE TITLE
Add vizier test script

### ISSUE THREAD

**Issue by ShvetankPrakash** [srivatsankrishnan/oss-arch-gym#22]
We should update this section's [documentation](https://oss-archgym.readthedocs.io/en/latest/installation.html#verify-vizier-installation) to have a standalone script for them to run in arch gym rather than asking them to do these steps:

-Make a copy of this script [vizier_dse.py](https://github.com/google/CFU-Playground/blob/main/proj/dse_template/vizier_dse.py)

-Remove line 10

-Replace line 40 to return random int ; for example: cycles, cells = 1, 1

-Run this file, sample output should look something like this: EXITING DSE…

which looks messy for us to ask of them.

**Comment by manan-garg1504** [comment]
Added vizier_verify.py script in the documentation branch, which is basically dse script with the above mentioned changes. Looks good?

**Comment by ShvetankPrakash** [comment]
Awesome perfect sounds good, can you just tag this issue and any other issues that are relevant in the PR so we know which PR ties to which issues to cross off :)
