### ISSUE TITLE
Multiple custom gym sample envs

### ISSUE THREAD

**Issue by ShvetankPrakash** [srivatsankrishnan/oss-arch-gym#27]
We have multiple example dummy environments under `arch_gym/envs/`. Let's just keep the example we like the best to clean it up.

**Comment by srivatsankrishnan** [comment]
@varun-k-s @aadyapipersenia04 Can you see one to retain? We can remove one of them which is not getting used.

**Comment by aadyapipersenia04** [comment]
custom_gym.py can be removed

**Comment by srivatsankrishnan** [comment]
Can you remove the file and send me a PR? Thanks.

**Comment by ShvetankPrakash** [comment]
I think custom_gym.py looked really clean to me so we might want to keep
that one?

**Comment by ShvetankPrakash** [comment]
@aadyapipersenia04 in addition to the changes we discussed last time to clean the environment up to make it easier to follow like the other example, clean up print formatting, etc. can you rename the dir to `CustomEnv` as well to make it look cleaner?
