### ISSUE TITLE
Add CFU documentation

### ISSUE THREAD

**Issue by srivatsankrishnan** [srivatsankrishnan/oss-arch-gym#28]
@manan-garg1504 @ShravaniKode Can you guys add and close  the CFU documentation thread?
Please work with @ShvetankPrakash  on the structure. I think we can reuse some of the stuff from the CFU materials itself.

**Comment by ShvetankPrakash** [comment]
@manan-garg1504, @ShravaniKode, Yash, and Karthik- I have started an outline here for the documentation to get things going:

https://github.com/srivatsankrishnan/oss-arch-gym/blob/documentation/docs/source/CFUPlayground.md

Hopefully this should help get things started and make it very easy for folks to simply fill the placeholders in quickly!

**Comment by ShvetankPrakash** [comment]
Move this https://github.com/srivatsankrishnan/oss-arch-gym/blob/main/docs/CFU_Installation_Steps.md into that new file I created.
