### ISSUE TITLE
DRAMSys Agents

### ISSUE THREAD

**Issue by ShvetankPrakash** [srivatsankrishnan/oss-arch-gym#41]
All agents work out of the box except for the following:
-train_brute_force.py
-train_ppo.py
-train_single_agent.py
-train_simpleEnv.py

**Comment by ShvetankPrakash** [comment]
@TensorTyrion9001 I was testing the DRAM agents again and found that the following were not working out of the box. Can you please resolve these?

**Comment by TensorTyrion9001** [comment]
Following Issues are resolved after resolving acme installation issue and train_ppo.py had issue regarding logging

**Comment by ShvetankPrakash** [comment]
Awesome @TensorTyrion9001, thanks!
